name: Simple Start Up 
on:
  push:
    branches: [main]
jobs: 
  build:
    name: Build my virtual OS 
    runs-on: Ubuntu-22.04 
    steps:
      - name: Checkout private repo remotely
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.repo_url }}
          path: /
          token: ${{ secrets.repo_token }}
      - name: Show hidden files 
        run: |
          cd home/
